export const ACTIONS = {
  WRITE_INITIATED: "WRITE_INITIATED",
  WRITE_PENDING: "WRITE_PENDING",
  WRITE_COMPLETE: "WRITE_COMPLETE",
  WRITE_SETTLED: "WRITE_SETTLED",
  WRITE_ERROR: "WRITE_ERROR",
  TRANSACTION_CONFIRMING: "TRANSACTION_CONFIRMING",
  TRANSACTION_CONFIRMED: "TRANSACTION_CONFIRMING",
  TRANSACTION_ERROR: "TRANSACTION_ERROR",
};
